<?php

const
	PERMIT_ADMIN = 1,
	PERMIT_TECHNICIAN = 0,

	TOKEN_INDEX = 'hering_access_token',
	PERMIT_INDEX = 'id_permit_list',

	SQLSTATE_DUPLICATE_KEY = 1062,
	SQLSTATE_TRANSACTION_TIME_OUT = 1205,
	SQLSTATE_TRUNCATE_COLUMN = 1406,
	SQLSTATE_FK_FAILS = 1452,
	SQLSTATE_TRANSACTION_MANY_CONCURRENTS = 1637,

	INIT_ACTION = 'init',
	ACTION_SERVER_CHAR_SEPARATOR = '.',

	//Compartilhado com o JAVASCRIPT ---------------------------------------------------------

	SPECIFIC_ERROR_EVENT_CROWDED = 1,

	ID_PROFILE_TECNICO = 1,
	ID_PROFILE_ADM = 1,
	ID_PROFILE_PARTICIPANT = 2,

	CUPOM_STATUS_APROVADO = 'A',
	CUPOM_STATUS_PENDENTE = 'P',
	CUPOM_STATUS_REPROVADO = 'R',
	CUPOM_STATUS_EXCLUIDO = 'X', 

	CONFIG_MODE_DEVELOPMENT = 1,
	CONFIG_MODE_PRODUCTION = 2,
	CURRENT_MODE = 1,
	
	// Comunicados
	COMUNICADO_CUPOM_RECEBIDO = 1,
	COMUNICADO_NOVA_SENHA = 2,

	// Ações de leitura e clique em e-mail
	EMAIL_ACAO_LEITURA = "1", 
	EMAIL_ACAO_CLIQUE = "6", 

	// Status de serviços
	SERVICO_STATUS_INICIADO = 1, 
	SERVICO_STATUS_PROCESSAMENTO = 2, 
	SERVICO_STATUS_FINALIZADO = 3, 
	SERVICO_STATUS_ERRO = 4, 

	// Serviços do sistema
	SERVICO_COMUNICADO_IMEDIATO = "ComunicadoImediato",

	// Comunicados - periodicidade
	COMUNICADO_PERIODICIDADE_IMEDIATA = "I", 
	COMUNICADO_PERIODICIDADE_AGENDADA = "A", 
	COMUNICADO_PERIODICIDADE_DIARIA = "D", 
	COMUNICADO_PERIODICIDADE_SEMANAL = "S", 
	COMUNICADO_PERIODICIDADE_MENSAL = "M",

	MAIL_CONTEUDO_IMAGEM = 'i', 
	MAIL_CONTEUDO_EMBED = 'e', 
	MAIL_CONTEUDO_REDIRECT = 'r',

	TYPE_RESTRICT_ACTION_TECH = 'T',
	TYPE_RESTRICT_ACTION_FREE = 'F',
	TYPE_RESTRICT_ACTION_AUTH = 'A',
	TYPE_RESTRICT_ACTION_ROLE = 'R';